cert: /path/to/your/fullchain.pem
key: /path/to/your/privkey.pem
users:
  - port: 5000
    password: some-very-long-password
    method: aes-256-cfb
    tls: true
    sni: user1.yourdomain.com
  - port: 5001
    password:  some-another-very-long-password
    method: aes-256-cfb
    tls: true
    sni: user2.yourdomain.com
services:
    - sni: default
      host: localhost
      port: 1443
      tls: true
    - sni: something.yourdomain.com
      host: 1.2.3.4
      port: 31337
      tls: true
